import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

Font.register({
  family: 'Oswald',
  src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf'
});

const styles = StyleSheet.create({
  page: {
    padding: 60,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 40,
    borderBottom: '2px solid #007AFF',
    paddingBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#050505',
    marginBottom: 5,
    letterSpacing: 2,
  },
  subtitle: {
    fontSize: 12,
    color: '#007AFF',
    textTransform: 'uppercase',
    letterSpacing: 4,
  },
  section: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    textTransform: 'uppercase',
    color: '#050505',
  },
  text: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#444444',
    marginBottom: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 60,
    right: 60,
    fontSize: 8,
    textAlign: 'center',
    color: '#999999',
    borderTop: '1px solid #eeeeee',
    paddingTop: 10,
  }
});

interface HelpersBookProps {
  data: {
    clientName: string;
    vision: string;
    recommendations: string[];
  }
}

export const HelpersBookTemplate = ({ data }: HelpersBookProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>DESIGN HELP DESK</Text>
        <Text style={styles.subtitle}>TECHNICAL BRIEF & HELPER&apos;S BOOK</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Project Vision</Text>
        <Text style={styles.text}>Prepared for: {data.clientName}</Text>
        <Text style={styles.text}>{data.vision}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Architectural Reasoning</Text>
        {data.recommendations.map((rec, i) => (
          <Text key={i} style={styles.text}>• {rec}</Text>
        ))}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Disclaimer</Text>
        <Text style={styles.text}>
          This document is generated by the Design Help Desk Reasoning Engine. 
          Specifications are indicative and subject to site survey and professional validation.
        </Text>
      </View>

      <View style={styles.footer}>
        <Text>&copy; 2026 Design Help Desk | Premium Interior Design Intelligence</Text>
      </View>
    </Page>
  </Document>
);
